language: php

php:
  - 7.1.9

branches:
  only:
    - staging
    - master
    - production

before_script:
  - echo 'construct general dependencies here before building on the designated branch'

script:
  - if [ $TRAVIS_BRANCH == "staging" ]; then
        echo 'staging build'; echo 'demonstrating multiple block executions';
    fi
  - if [ $TRAVIS_PULL_REQUEST == true && $TRAVIS_BRANCH == "master" ]; then
        echo 'master build';
    fi
  - if [ $TRAVIS_PULL_REQUEST == true && $TRAVIS_BRANCH == "production" ]; then
        echo 'production build';
    fi

after_script:
  - if [ $TRAVIS_BRANCH == "staging" ]; then
        echo 'deploy app to staging environment with forge';
    fi
  - if [ $TRAVIS_BRANCH == "master" ]; then
        echo 'deploy app to development environment with forge';
    fi
  - if [ $TRAVIS_BRANCH == "production" ]; then
        echo 'deploy app to production environment with forge';
    fi
