language: php

php:
  - 7.1.9

branches:
  only:
    - staging
    - master

before_script:
  - echo 'before master'

script:
  if: (branch = staging)
    - echo 'staging build'
  if: (branch = master) AND (NOT (type IN (push, pull_request)))
    - echo 'master build'

after_script:
  - echo 'done master'
