language: node_js

node_js:
- node

env:
- SERVER_IP_ADDRESS=18.217.253.185

before_install:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_71597800fa05_key -iv $encrypted_71597800fa05_iv
  -in deploy_key.enc -out ./deploy_key -d
- ssh-add ./deploy_key
- ssh -i ./deploy_key ubuntu@18.217.253.185 pwd

after_success:
- echo "build complete kenvin"

