language: php

php:
  - 7.1.9

branches:
  only:
    - staging
    - master

before_script:
  - echo 'before building on the designated branch'

script:
  - if [ $TRAVIS_BRANCH == "staging" ]; then
        echo 'staging build';
    fi
  - if [ $TRAVIS_BRANCH == "master" ]; then
        echo 'master build';
    fi

after_script:
  - echo 'after building on associated branch';
